version: '3'
services:
  web:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
